/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function highlight(code: string, language: "js" | "jsx" | "ts"| "tsx" | "go" | "c" | "py" | "rb", options?: Options | undefined | null): string

export interface Options {
  theme?: "default" | "github-light" | "github-dark"
}
